version: "3.1"
services:
    backend:
        image: webdevops/php-nginx:7.2
        container_name: ${CONTAINER_PREFIX}_backend
        restart: always
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ../:/var/www/html
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/html${DOCUMENT_ROOT_DIRECTORY}
            - NGINX_HOST=${HTTP_HOST}
        working_dir: /var/www/html
    mysql:
        image: mysql
        container_name: ${CONTAINER_PREFIX}_mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
          - ./persistence/mysql:/var/lib/mysql
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: ${CONTAINER_PREFIX}_pma
        links:
          - mysql:db
        ports:
          - "${PMA_PORT}:80"
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
